spring:
  datasource:
    url: jdbc:mysql://localhost:3306/runninggo
    username: minjee
    password: kimmj1106!
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  messages:
    basename: error_messages
  mail:
    host: smtp.gmail.com
    port: 587
    username: running.go77@gmail.com
    password: mdehnyumyeobxvfk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mybatis:
  type-aliases-package: com.runninggo.toy.domain
  mapper-locations: mapper/**/**.xml